### ISSUE TITLE
V2.2 - Make checkbox for show user profile default checked if user has selected it

### ISSUE THREAD

**Issue by mctian** [chainmaporg/cmp#159]

**Comment by gezhao** [comment]
The current user profile update has a problem. If customer selects the box the setting did not reflect in next time the customer open "update profile".

**Comment by gezhao** [comment]
@thedhrubo Not sure if you have fixed this, seems you were working on this before?

**Comment by thedhrubo** [comment]
Hi george,

Sorry i did not work on this issue.

Thanks
Dhrubo
