### ISSUE TITLE
V2.2 - 10.Solution Map for case difference

### ISSUE THREAD

**Issue by gezhao** [chainmaporg/cmp#167]
Case:

Tell me about differences between Proofs-of-Computation (Work, stake, etch) at blockchain. Explain me the key differences.

Expected:

-A Map (nodes) which can be generate a list of tuples (in csv) such as:
"name", "description", "link", "expected learning time" ...or something relevant. And we can load into database (mysql),
-The DB schema and contents

**Comment by LawrenceSingWong** [comment]
The difference between these concepts are crucial in blockchain.
Proof of Work
A proof-of-work ([PoW](https://en.wikipedia.org/wiki/Proof-of-work_system)) system (or protocol, or function) is an economic measure to deter denial of service attacks and other service abuses such as spam on a network by requiring some work from the service requester, usually meaning processing time by a computer. 

Proof of Stake
Proof of stake ([PoS](https://en.wikipedia.org/wiki/Proof-of-stake)) is a type of algorithm by which a cryptocurrency blockchain network aims to achieve distributed consensus.

**Comment by LawrenceSingWong** [comment]
Proof of Computation concepts in Blockchain, the difference between these concepts are crucial in blockchain.

Proof of Work
A proof-of-work ([PoW](https://en.wikipedia.org/wiki/Proof-of-work_system)) system (or protocol, or function) is an economic measure to deter denial of service attacks and other service abuses such as spam on a network by requiring some work from the service requester, usually meaning processing time by a computer.

Proof of Stake
Proof of stake ([PoS](https://en.wikipedia.org/wiki/Proof-of-stake)) is a type of algorithm by which a cryptocurrency blockchain network aims to achieve distributed consensus.

Delegated Proof of Stake([DPoS](https://www.mycryptopedia.com/delegated-proof-stake-dpos-explained/)) is an alternative consensus mechanism that requires coin holders to vote for “delegates”, who are then responsible for validating transactions and maintaining the blockchain. DPoS is an alternative to the more commonly known, Proof-of-Stake (PoS) model, which requires miners to put up a stake in the required cryptocurrency before they are  able to process transactions and add them to the blockchain. 

[Consensus](https://en.wikipedia.org/wiki/Consensus_(computer_science)) 
A fundamental problem in distributed computing and multi-agent systems is to achieve overall system reliability in the presence of a number of faulty processes. This often requires processes to agree on some data value that is needed during computation. 

[Fault tolerance](https://en.wikipedia.org/wiki/Fault_tolerance) is the property that enables a system to continue operating properly in the event of the failure of (or one or more faults within) some of its components.

**Comment by gezhao** [comment]
I saw you have a word doc sending in wechat...and this should be done within github. So we have all records and the issue update should have all info.
