### ISSUE TITLE
V2.2 - Search Engine "Search All" return only news section

### ISSUE THREAD

**Issue by gezhao** [chainmaporg/cmp#205]
Test case:

1. Existing chainmap.org Home page, search on "All" and put keywords on "insurance".
2. Return results all news.

Even if we increase to 30 (another issue fired) for registered users. Still this problem exists.

So should we turn off "All" option for V2.2 version as a quick fix?

**Comment by XingfeiYu** [comment]
Fixed, please try it.

**Comment by gezhao** [comment]
I tested and saw news and whitepaper in. not just news.
