### ISSUE TITLE
Write a article to explain the AI recommendation in ChainMap

### ISSUE THREAD

**Issue by gezhao** [chainmaporg/cmp#211]
Thanks for the work on AI recommendation, Mason.

Now it is a warp-up time, please write a article to explain the technology we are using.

A google doc or a wiki is fine on format!

The other people taking over your task shall be able to understand by reading your article.

You can suggest further things to do in your opinion.

Thanks!

**Comment by mctian** [comment]
I sent you a word document in slack.
